### ISSUE TITLE
no count field in sevilleta dataset 232

### ISSUE THREAD

**Issue by mauriemma** [hurlbertlab/core-transient#31]
No 'count' data for this dataset. Not sure where to go from here.  Check out the saved scripts I have so far to see what direction we could possibly take it.  Also, on a side note can you confirm the nested sites concatenated here as well?

**Comment by ethanwhite** [comment]
Looks like this is the Sevilleta rodent data. Each line in the raw data is an individual organism, so in order to get counts for a date/site/species combination you'll need to group the data by the relevant fields and count the number of relevant columns and get counts of the number of rows for each grouping.
