### ISSUE TITLE
double checking spatial grain d251

### ISSUE THREAD

**Issue by ssnell6** [hurlbertlab/core-transient#66]
I wanted to confirm that the spatial resolution was 10km. I thought that the area of fish species being caught in the tow nets would be the grain rather than the dimensions of the actual net.

https://portal.lternet.edu/nis/metadataviewer?packageid=knb-lter-pal.100.1

"All seabird censuses were thus conducted within approximately 100 kms of Palmer Station while traversing a sampling grid with stations at 10km intervals. The first two days (18-20 January) of this cruise were spent covering the selected grid as rapidly as possible resulting in 45 transects spaced at 45-60 minute intervals. There were no stops at the 10km stations during this Fast Grid phase. Upon completion of the Fast Grid, a force 12 gale suspended data collection for 24 hours. From January 22-25 the grid direction was reversed and the grid repeated. During this Slow Grid phase, 2-M net tows were done at 10km intervals and BOPS and 1-M and 2-M net tows every 20 km. All seabird censuses during the cruise were done using the procedures outlined in the previous paragraph."

**Comment by ssnell6** [comment]
Actually, I can't find site data besides a cruise name and study name. Would those be good enough to proceed?

**Comment by ahhurlbert** [comment]
We have decided that cruise-based bird oceanic bird surveys are not well suited for characterizing "assemblages" over time, so don't worry about working on this dataset or others like it.

**Comment by ssnell6** [comment]
Ok. Should I mark OBIS datasets and this one with a 5 in the formatting table?

**Comment by ahhurlbert** [comment]
Yes. Our decision was primarily about pelagic datasets on the open ocean where there is no physical template (like a reef, or bottom sediments) that defines a site. Any particular lat-long in the ocean doesn't really define a site, since the ocean conditions (productivity, temperature, etc) at that lat-long can change over time and organisms like birds and fish will just move around to follow conditions. Note that some OBIS datasets actually are in systems where there is some physical template, but many of them are not.

 And go ahead and close any other issues that we resolved yesterday.

**Comment by ssnell6** [comment]
Ok thanks. I will go through and update.
