### ISSUE TITLE
Noting which dataset IDs have lots of lat longs attached to them

### ISSUE THREAD

**Issue by ssnell6** [hurlbertlab/core-transient#79]
For plotting I am trying to find the mid-point of the study but some studies have sites that are far from one another or many sites. I wanted to make a list of species with a lot of sites so we can deal with them later during plotting & analysis.

d1 - BBS
d247 - Mosquitoes of North America with emphasis in the midwestern United States
d248 - CA Channel islands and Santa Barbara
d269 - Species composition and population fluctuations of alpine bird communities during 38 years in the Scandinavian mountain range
d289 - Long-term stem inventory data from tropical rain forest plots in Australia: trees >10cm dbh
d308 - mountain birdwatch
d309 - international bottom trawl survey
d315 - monitoring abundance of butterflies in the UK - sites spread across country

**Comment by ahhurlbert** [comment]
@ssnell6 I noticed that the lat-longs entered into the data formatting table for d33 are not quite right, and so want to make sure you double check all of them.

According to the paper (http://plankt.oxfordjournals.org/content/32/5/643.full), the site's lat long is given as 50° 15.00′N, 4° 13.02′W. 

Since, we are recording lat and long in decimal degrees, this means it should be 50.25 N (i.e. 15 minutes out of 60), and 4.217 W (13.02/60).

So double check that all lat-longs that were reported in degrees-minutes-seconds actually got converted appropriately to decimal degrees.

DD = degrees + minutes/60 + seconds/3600

**Comment by ssnell6** [comment]
Oh man, that's not good. I used an online converter to decimal degrees so its possible theyre off. I'll double check ASAP

**Comment by ssnell6** [comment]
Any ideas on how to deal with the mosquito dataset? There are 542,145 entries with all different locations. Maybe an R package that geolocates based on location name?
