### ISSUE TITLE
cleaning script for d222

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient#93]
@ssnell6 The raw data is available here http://onlinelibrary.wiley.com/doi/10.1890/10-0404.1/abstract, so I think this is the data that we want to clean in the script rather than the modified version that you obtained from the Yenni et al. repo. She seems to have aggregated individual quadrats so that information is lost (even if we eventually will also aggregate them).

Using Yenni et al. is a source is fine for any instances where the raw data are otherwise not easily accessible, e.g. thru Ecological Archives, LTER, Dryad, etc.

Also, it would probably be better to lump rather than remove some current "bad_sp". For example, "Antennaria.spp_" could be lumped with "Antennaria.rosea" since there is no other Antennaria species (and all of the data is actually present under the former code rather than the latter). Same for Carex.

**Comment by ssnell6** [comment]
Want to double check that the "area" field in allrecords_cover.csv is the cover calculation, because it is a bit confusing. The metadata description says this is a measure of the area of the polygon, since all of the quad data points are stored as shapefiles. However, it is suspicious bc there are no zero values.

**Comment by ahhurlbert** [comment]
As specified here, "area" is the area in m2:

http://esapubs.org/archive/ecol/E091/243/metadata.htm
